name: CI/CD Pipeline for Next.js with Docker

on:
  push:
    branches:
      - main  

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 

      - name: Install Dependencies
        run: npm install  

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: install-dependencies  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Tests
        run: npm test  

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: run-tests  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ayagallal/promptopia .  # ✅ Builds the Docker image with your repository name

      - name: Save Docker Image as Artifact
        run: docker save ayagallal/promptopia -o promptopia.tar  # ✅ Saves the image as a `.tar` file

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: promptopia.tar  # ✅ Uploads the image file as an artifact

  deploy:
    name: Deploy to Registry
    runs-on: ubuntu-latest
    needs: build-docker  # ✅ This job runs only if 'build-docker' is successful
    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: .  # ✅ Downloads the image artifact

      - name: Load Docker Image
        run: docker load -i promptopia.tar  # ✅ Loads the saved `.tar` image into Docker

      - name: Tag and Push Image to Docker Hub
        run: |
          docker tag ayagallal/promptopia ayagallal/promptopia:latest  # ✅ Tags the image
          docker push ayagallal/promptopia:latest  # ✅ Pushes the image to Docker Hub
