name: CI/CD Pipeline for Next.js with Docker

on:
  push:
    branches:
      - main  

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 

      - name: Install Dependencies
        run: npm install  

      # ✅ Explicitly install Jest & Babel to fix missing dependencies
      - name: Ensure Jest & Babel are installed
        run: npm install --save-dev jest babel-jest @babel/preset-env @babel/preset-react

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: install-dependencies  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci  # ✅ Ensures dependencies are installed before running tests

      - name: Run Jest Tests
        run: npx jest  # ✅ Uses npx to run Jest without global installation

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: run-tests  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Docker Hub
        run: echo "dckr_pat_9m8zxXatJcArYboBOjGWboxJx84" | docker login -u "ayagallal" --password-stdin

      - name: Build Docker Image
        run: docker build --no-cache -t ayagallal/promptopia .  # ✅ Added --no-cache to prevent old layers from interfering

      - name: Save Docker Image as Artifact
        run: docker save -o promptopia.tar ayagallal/promptopia  # ✅ Corrected the order of arguments

      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: promptopia.tar  # ✅ Uploads the image file as an artifact

  deploy:
    name: Deploy to Registry
    runs-on: ubuntu-latest
    needs: build-docker  # ✅ This job runs only if 'build-docker' is successful
    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .  # ✅ Downloads the image artifact

      - name: Load Docker Image
        run: docker load -i promptopia.tar  # ✅ Loads the saved `.tar` image into Docker

      - name: Tag and Push Image to Docker Hub
        run: |
          docker tag ayagallal/promptopia ayagallal/promptopia:latest  # ✅ Tags the image correctly
          docker push ayagallal/promptopia:latest  # ✅ Pushes the image to Docker Hub
